server:
  port: 8088

spring:
  application:
    name: servicio-pagos
  datasource:
    url: jdbc:postgresql://localhost:5432/spartan_pagos
    username: spartan
    password: spartan
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
