server:
  port: 8083

spring:
  application:
    name: servicio-entrenamiento
  datasource:
    url: jdbc:postgresql://localhost:5432/spartan_entrenamiento
    username: spartan
    password: spartan
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  kafka:
    bootstrap-servers: localhost:9092
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

aws:
  region: us-east-1

spartan:
  multimedia:
    video-bucket: spartan-gym-media-videos
    photo-bucket: spartan-gym-media-photos
    cloudfront-domain: ""
    presigned-url-expiration-minutes: 60
