server:
  port: 8087

spring:
  application:
    name: servicio-social
  datasource:
    url: jdbc:postgresql://localhost:5432/spartan_social
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092

aws:
  neptune:
    endpoint: localhost
    port: 8182
