apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME}
  namespace: spartan-gym-${ENVIRONMENT}
  labels:
    app: ${SERVICE_NAME}
    app.kubernetes.io/name: ${SERVICE_NAME}
    app.kubernetes.io/part-of: spartan-golden-gym
    environment: ${ENVIRONMENT}
spec:
  type: ClusterIP
  selector:
    app: ${SERVICE_NAME}
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
